version: "3.8"

services:
  test_db_server:
    image: postgres
    volumes:
      - test_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/environment/test/.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test_env

  test_tweet_server:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5500
    env_file:
      - ./backend/environment/test/.env
    ports:
      - 5500:5500
    depends_on:
      test_db_server:
        condition: service_healthy
    networks:
      - test_env

volumes:
    test_postgres_data:

networks:
  test_env:
    driver: bridge
