version: "3.8"

services:
  db_server:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/environment/prod/.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod_network

  tweet_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: bash -c "alembic upgrade heads && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5000"
    env_file:
      - ./backend/environment/prod/.env
    ports:
      - 5000:5000
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - prod_network

  tweet_web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/:/ngnix/
    ports:
      - 80:80
    depends_on:
      - tweet_api
    networks:
      - prod_network

volumes:
    postgres_data:

networks:
  prod_network:
    driver: bridge
