FROM python:3.8.1-alpine

WORKDIR /backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

COPY ./environment/test/requirements.txt /backend/requirements.txt

RUN set -eux \
  && apk add --no-cache --virtual .build-deps build-base \
     libressl-dev libffi-dev gcc musl-dev python3-dev \
     libc-dev libxslt-dev libxml2-dev bash \
     postgresql-dev \
  && pip install --upgrade pip setuptools wheel \
  && pip install -r /backend/requirements.txt \
  && rm -rf /root/.cache/pip

COPY ./app /backend/app
COPY ./tests /backend/tests
COPY ./alembic.ini /backend/alembic.ini
COPY ./apply_migrations.py /backend/apply_migrations.py
COPY ./setup.cfg /backend/setup.cfg
COPY ./environment/test/.env /backend/.env
